use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=src/serverlist.proto");
    println!("cargo:rerun-if-changed=src/config/config.json");

    let out_dir_str = std::env::var("OUT_DIR").unwrap();
    let out_dir = PathBuf::from(&out_dir_str);
    println!("OUT_DIR: {}", out_dir_str);

    match prost_build::compile_protos(&["src/serverlist.proto"], &["src/"]) {
        Ok(_) => println!("Proto compilation successful"),
        Err(e) => println!("Proto compilation failed: {:?}", e),
    }

    // --- M6-b anti-reverse: obfuscate config.json at compile time ---
    //
    // config.json contains the portal URL (157.90.107.2:8090). Shipped
    // plaintext via include_str!, `strings launcher.exe | grep 192.168`
    // trivially lifts it. A per-build rolling-XOR masks the bytes in the
    // `.rdata` section so that plaintext scan returns nothing. Decryption
    // happens once at first CONFIG access and is cached by the Lazy in
    // src/config.rs.
    //
    // The XOR key is regenerated per build (not a deterministic constant)
    // so attackers can't pre-compute a decrypt against a known key from a
    // previous release.
    let config_path = PathBuf::from("src/config/config.json");
    let config_bytes = fs::read(&config_path)?;

    // 32-byte key — wide enough to resist a casual byte-frequency attack.
    // Seeded from build-time nanos ^ bytes.len so consecutive builds get
    // different keys without pulling in a full CSPRNG build dep.
    let mut key = [0u8; 32];
    let nanos = SystemTime::now().duration_since(UNIX_EPOCH)?.as_nanos() as u64;
    for (i, slot) in key.iter_mut().enumerate() {
        let m = nanos.rotate_left((i as u32) * 7);
        *slot = ((m >> ((i % 8) * 8)) as u8) ^ (i as u8) ^ (config_bytes.len() as u8);
    }

    let obfuscated: Vec<u8> = config_bytes
        .iter()
        .enumerate()
        .map(|(i, &b)| b ^ key[i % key.len()])
        .collect();

    let mut out = String::new();
    out.push_str("// @generated by build.rs — DO NOT EDIT\n");
    out.push_str("// Obfuscated config.json; decrypted lazily in src/config.rs.\n\n");
    out.push_str(&format!(
        "pub const CONFIG_OBF: &[u8] = &{:?};\n",
        obfuscated
    ));
    out.push_str(&format!("pub const CONFIG_KEY: [u8; 32] = {:?};\n", key));

    fs::write(out_dir.join("config_obf.rs"), out)?;

    Ok(())
}
